version: '3'

services:

  postgres:
    image: postgres
    container_name: postgres

    environment:
      POSTGRES_USER: ${DB_USER:postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:secret}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    networks:
      - global-default

  jaeger:
    image: jaegertracing/all-in-one:1.32
    container_name: jaeger

    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  redis:
    image: redis
    container_name: redis

    ports:
      - 6379:6379

    networks:
      - global-default

    volumes:
      - .data/redis:/data


networks:
  global-default:
    external: true
